########## 开发环境配置文件
###### 设置项目启动端口号
server:
  port: 12306
spring:
  ######配置项目应用名
  application:
    name: addrook_backend
  ###### 开启 Spring Boot Bean Id Override 机制
  main:
    allow-bean-definition-overriding: true
  ###### 配置 DataSource 信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/addrooks_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&all
    username: root
    password: root
    ###### 配置druid 作为数据库连接池信息
    druid:
      min-idle: 3
      max-active: 15
      initial-size: 5
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000